### ISSUE TITLE
Mime returning undefined when try to find out mime type of files with a .(dot) in the beginning of the name

### ISSUE THREAD

**Issue by omarpta** [benmerckx/mime#3]
If you try to get Mime Type from files like:
**.bashrc
.history**

You will receive undefined.
You should lookup the file itself (**like require('mime') from Nodejs does**) not just the extension.

Thanks

**Comment by benmerckx** [comment]
Undefined (or null in haxe) is expected when the file type is not found. Neither bashrc nor history are defined in mime db. You'll want to do a null check and define a default mime type in that case. If you're expecting text you might default to text/plain, otherwise application/octet-stream will do.
